### ISSUE TITLE
crypto.createCipheriv broken on Node v6+

### ISSUE THREAD

**Issue by codebling** [MaxMotovilov/galette#2]
[cipher.js](https://github.com/MaxMotovilov/galette/blob/9326e9a713801ebc71367406f0ee47d91347005c/lib/cipher.js) calls `crypto.createCipheriv()` on [line 27](https://github.com/MaxMotovilov/galette/blob/9326e9a713801ebc71367406f0ee47d91347005c/lib/cipher.js#L27) (and `crypto.createDecipheriv()` on [line 54](https://github.com/MaxMotovilov/galette/blob/9326e9a713801ebc71367406f0ee47d91347005c/lib/cipher.js#L54)) passing a binary-encoded String, which [is unsupported in Node v6+](https://nodejs.org/dist/latest-v6.x/docs/api/crypto.html#crypto_crypto_createcipheriv_algorithm_key_iv). This results in the following error: 
```
session.28f514e928f5: Error: Invalid IV length
    at Error (native)
    at new Cipheriv (crypto.js:190:16)
    at Object.Cipheriv (crypto.js:188:12)
    at InternalFieldObject.ondone (/project/node_modules/galette/lib/cipher.js:27:23)
```

PR forthcoming.

**Comment by MaxMotovilov** [comment]
PR would be much appreciated - didn't get to Node 6+ yet.

**Comment by MaxMotovilov** [comment]
Best I can tell, dropping 0.8- support is not likely to inconvenience anyone.
